import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.scss'
import {Modal} from "../components/Modal";
import {ModalTrigger} from "../components/ModalTrigger";
import {ModalContent} from "../components/ModalContent";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Modal>
          <ModalTrigger>Trigger my modal</ModalTrigger>
          <ModalContent>
            <h2 style={{ marginTop: 0 }}>Demo</h2>
            <p>
              Pellentesque habitant morbi tristique senectus et netus et malesuada
              fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
              ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
              egestas semper. Aenean ultricies mi vitae est. Mauris placerat
              eleifend leo.
            </p>
            <p>
              Pellentesque habitant morbi tristique senectus et netus et malesuada
              fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
              ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
              egestas semper. Aenean ultricies mi vitae est. Mauris placerat
              eleifend leo.
            </p>
          </ModalContent>
        </Modal>
      </main>
    </div>
  )
}

export default Home
